openapi: 3.0.0
info:
  title: API Documentación con OpenAPI
  description: API de ejemplo documentada con OpenAPI y Swagger
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Servidor de desarrollo

paths:
  /obtenerClientes:
    get:
      description: Obtiene lista de clientes
      operationId: clienteRut
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listaClientes"
        "204":
          description: Sin Contenido
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorGenerico'
          description: error 400
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorGenerico'
          description: Acceso no permitido al contenido
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorGenerico'
          description: Cliente no encontrado
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorGenerico'
          description: Error interno      
      tags:
        - private
      x-codegen-request-body-name: request
      x-eov-operation-handler: controllers/clientes      
    



  /api/data/score:
    get:
      summary: Obtener todos los clientes
      description: Retorna una lista de todos los clientes registrados en la base de datos.
      operationId: todoClientes
      x-controller: clienteController
      responses:
        "200":
          description: Lista de clientes obtenida correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  clientes:
                    type: array
                    items:
                      $ref: "#/components/schemas/Cliente"
        "500":
          description: Error en el servidor.
      x-codegen-request-body-name: request
      x-eov-operation-handler: controllers/generaDocumentoController       

components:
  schemas:
    listaClientes:
      type: array
      items:
        $ref: '#/components/schemas/Cliente'

    Cliente:
      type: object
      properties:
        rut:
          type: string
          example: "12345678-9"
        datos:
          type: array
          items:
            $ref: '#/components/schemas/DatoCliente'

    DatoCliente:
      type: object
      properties:
        nombreCompleto:
          type: string
          example: "Juan Pérez"
        Cupo:
          type: string
          example: "500000"
        tipoTarjeta:
          type: string
          example: "Visa Gold"

    ErrorGenerico:
      type: object
      properties:
        message:
          type: string
          example: "Ocurrió un error inesperado"
        code:
          type: integer
          example: 500

