openapi: 3.0.0
info:
  title: API Documentación con OpenAPI
  description: API de ejemplo documentada con OpenAPI y Swagger
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Servidor de desarrollo

paths:
  /api/data/score:
    get:
      summary: Obtener todos los clientes
      description: Retorna una lista de todos los clientes registrados en la base de datos.
      operationId: todoClientes
      x-controller: clienteController
      responses:
        "200":
          description: Lista de clientes obtenida correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  clientes:
                    type: array
                    items:
                      $ref: "#/components/schemas/Cliente"
        "500":
          description: Error en el servidor.

components:
  schemas:
    Cliente:
      type: object
      properties:
        rut:
          type: string
          example: "12345678-9"
        datos:
          type: array
          items:
            $ref: "#/components/schemas/DatoCliente"

    DatoCliente:
      type: object
      properties:
        nombreCompleto:
          type: string
          example: "Juan Pérez"
        Cupo:
          type: string
          example: "500000"
        tipoTarjeta:
          type: string
          example: "Visa Gold"
