openapi: 3.0.0
info:
  title: API Documentación con OpenAPI
  description: API de ejemplo documentada con OpenAPI y Swagger
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Servidor de desarrollo

paths:
  /obtenerClientes:
    get:
      description: Obtiene lista de clientes
      operationId: clienteRut
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listaClientes"
        "204":
          description: Sin Contenido
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorGenerico'
          description: error 400
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorGenerico'
          description: Acceso no permitido al contenido
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorGenerico'
          description: Cliente no encontrado
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorGenerico'
          description: Error interno      
      tags:
        - Clientes
      x-codegen-request-body-name: request
      x-eov-operation-handler: clientes
      
  /api/data/crearNuevoCliente:
    post:
      summary: Crear nuevo cliente
      description: Crea un nuevo cliente en la base de datos.
      operationId: crearCliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cliente"
      responses:
        "201":
          description: Cliente creado correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  msg:
                    type: string
                    example: cliente guardado correctamente
        "400":
          description: Error en la solicitud
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorGenerico'
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorGenerico'
      tags:
        - Clientes
      x-codegen-request-body-name: request
      x-eov-operation-handler: clientes
    
components:
  schemas:
  
    Cliente:
      type: object
      required:
        - rut
        - datos
      properties:
        rut:
          type: string
          example: "12345678-9"
        datos:
          type: array
          items:
            type: object
            required:
              - nombreCompleto
              - cupoClp
              - cupoUsd
              - tipoTarjeta
            properties:
              nombreCompleto:
                type: string
                example: "Juan Pérez"
              cupoClp:
                type: string
                example: "500000"
              cupoUsd:
                type: string
                example: "600"
              tipoTarjeta:
                type: string
                example: "Visa Gold"

    DatoCliente:
      type: object
      properties:
        nombreCompleto:
          type: string
          example: "Juan Pérez"
        Cupo:
          type: string
          example: "500000"
        tipoTarjeta:
          type: string
          example: "Visa Gold"

    RespuestaCreacion:
      type: object
      properties:
        ok:
          type: boolean
          example: true
        msg:
          type: string
          example: Cliente creado correctamente
    listaClientes:
      type: array
      items:
        $ref: "#/components/schemas/Cliente"

    ErrorGenerico:
      type: object
      properties:
        message:
          type: string
          example: Ocurrió un error inesperado
        code:
          type: integer
          example: 500

